[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && gunicorn --worker-class eventlet -w 1 server:app --bind 0.0.0.0:$PORT --timeout 120"
